### ISSUE TITLE
Vertaisarviointi

### ISSUE THREAD

**Issue by 070470** [HoolaBoola/tiralabra#2]
(Projekti ladattu 20.2.2022 klo 10:53)

# Vertaisarviointi

## Yleisiä huomioita

Projekti on kaiken kaikkiaan erinomaisesti ja ammattimaisen oloisesti tehty, dokumentaatiota ja testausta myöten. Rust ei ole minulle ennestään tuttu kieli - joskin sen verran intuitiivinen, että pystyin lukemaan koodia ongelmitta - joten en pysty sanomaan paljoakaan kielen käytännöistä, mutta koodi vaikutti kompaktilta ja se oli selitetty hyvin auki. Ohjelman käyttöohjeet olivat selkeät ja se toimi hyvin kaikilla syöttämilläni lausekkeilla, kuten myös testaus, joka oli toteutettu kattavasti. Ohjelman eri osat oli jaoteltu ja toteutettu johdonmukaisesti, ja kommentointi oli selkeää. Todella hyvää jälkeä!

## Parannuksia

Koodia tutkiessani en löytänyt oikeastaan mitään huomauttamisen arvoista. Ainoa mieleen tuleva asia liittyi nollalla jakamiseen - mikäli ohjelmalle syötetyssä lausekkeessa on jokin muu vika (esim. ylimääräisiä tai puuttuvia sulkeisia), ohjelma kertoo, mikä mättää. Mikäli ongelma on nollalla jakamisessa, tulee outputtina kuitenkin ainoastaan "NaN". Nuo muut mainitsemani ongelmat tosin liittyvät syntaksiin eivätkä laskutoimitusten sisältöön, joten ehkä tämä oli tietoinen rajanveto, mutta ei suuri asia kummassakaan tapauksessa.

**Comment by HoolaBoola** [comment]
Kiitos vertaisarvioinnista. Tuo nollalla jakaminen tarkoituksella tuotti "NaN", mutta mainittuasi sen tajusin itsekin että se ei ole paras ratkaisu (nyt 1/0 = inf, -1/0 = -inf, 0/0 = NaN, Rustin standardikirjastossa määritellyllä tavalla). NaN tai inf ei siis ole virhe (eikä siksi siinä lue virheviestiä)
